apiVersion: apps/v1
kind: Deployment
metadata:
  name: moovebeta-savings-dep
spec:
  selector:
    matchLabels:
      app: moovebeta-k8s-dep
  replicas: 3
  template:
    metadata:
      labels:
        app: moovebeta-k8s-dep
    spec:
      containers:
        - name: moovebeta-savings-image
          image: 33084686/moovebeta_savings:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_NAME
              value: personal_savings
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: BetaSavings@123

---

apiVersion: v1
kind: Service
metadata:
  name: moovebeta-savings-service
spec:
  selector:
    app: moovebeta-k8s-dep
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort